export const leads = [
    {
        companyName: "BBC",
        category: "news", 
        country: "England",
        website: "https://www.bbc.com",
        primaryEmail: "editor@bbc.com",
        secondaryEmail: "subeditor@bbc.com",
        phone: "0121312466",
        whatsApp: "01323546576",
        socialUrl: "https://www.facebook.com/bbcnews",
        linkedinUrl: "https://www.linkedin.com/company/bbc/?originalSubdomain=uk",
        employee: "Mark Don",
        employeeContact: "https://www.facebook.com/bbcnews",
        othersInfo: "We’re impartial and independent, and every day we create distinctive, world-class programmes and content which inform, educate and entertain millions of people in the UK and around the world."
    },
    {
        companyName: "CNN",
        category: "news", 
        country: "United States",
        website: "www.cnn.com",
        primaryEmail: "contact@cnn.com",
        secondaryEmail: "subeditor@bbc.com",
        phone: "404-827-1500",
        whatsApp: "01323546576",
        socialUrl: "https://www.facebook.com/bbcnews",
        linkedinUrl: "https://www.linkedin.com/company/cnn/",
        employee: "Anderson Cooper",
        employeeContact: "https://twitter.com/andersoncooper",
        othersInfo: "CNN operates as a division of WarnerMedia, with headquarters in Atlanta, Georgia, and studios in New York City."
    },
    {
        companyName: "Al Jazeera",
        category: "news", 
        country: "Qatar",
        website: "www.aljazeera.com",
        secondaryEmail: "subeditor@bbc.com",
        primaryEmail: "info@aljazeera.net",
        phone: "+974 4489 2555",
        whatsApp: "01323546576",
        facebookUrl: "https://www.facebook.com/aljazeera",
        linkedinUrl: "https://www.linkedin.com/company/al-jazeera-media-network/",
        employee: "Mehdi Hasan",
        employeeContact: "https://twitter.com/mehdirhasan",
        othersInfo: "Al Jazeera is a Qatari state-funded broadcaster in Doha, Qatar, owned by the Al Jazeera Media Network. Initially launched as a satellite TV news channel, it has since expanded into a network with several outlets."
    },
    {
        companyName: "The New York Times",
        category: "news", 
        country: "United States",
        website: "www.nytimes.com",
        primaryEmail: "news-tips@nytimes.com",
        secondaryEmail: "subeditor@bbc.com",
        phone: "800-NYTIMES",
        whatsApp: "01323546576",
        twitterUrl: "https://twitter.com/nytimes",
        linkedinUrl: "https://www.linkedin.com/company/the-new-york-times/",
        employee: "Dean Baquet",
        employeeContact: "https://twitter.com/deanbaquet",
        othersInfo: "The New York Times is an American newspaper based in New York City with worldwide influence and readership. Founded in 1851, the paper has won 130 Pulitzer Prizes, more than any other newspaper."
    },
    {
        companyName: "The Guardian",
        category: "news", 
        country: "England",
        website: "www.theguardian.com",
        primaryEmail: "reader@theguardian.com",
        secondaryEmail: "subeditor@bbc.com",
        phone: "+44 (0) 20 3353 2000",
        whatsApp: "01323546576",
        twitterUrl: "https://twitter.com/guardian",
        linkedinUrl: "https://www.linkedin.com/company/theguardian/",
        employee: "Katharine Viner",
        employeeContact: "https://twitter.com/kathviner",
        othersInfo: "The Guardian is a British daily newspaper. It was founded in 1821 as The Manchester Guardian, and changed its name in 1959. It has a long history of editorial and political independence."
    }
];
