// FOR AUTH
export const LOGIN = "LOGIN";
export const LOGOUT = "LOGOUT";
export const ERROR = "ERROR";
export const MESSAGE = "MESSAGE";

export const START_LOADING = "START_LOADING";
export const END_LOADING = "END_LOADING";

// FOR CATEGORY
export const CREATE_CATEGORY = 'CREATE_CATEGORY';
export const UPDATE_CATEGORY = 'UPDATE_CATEGORY';
export const DELETE_CATEGORY = 'DELETE_CATEGORY';
export const FETCH_ALL_CATEGORY = 'FETCH_ALL';

// FOR LEAD

export const CREATE_LEAD = "CREATE_LEAD";
export const GET_ALL_LEAD = "GET_ALL_LEAD";


// FOR PRODUCT
export const ADD_PRODUCT = "ADD_PRODUCT";
export const UPDATE_PRODUCT = "UPDATE_PRODUCT";
export const DELETE_PRODUCT = "DELETE_PRODUCT";
export const FETCH_ALL_PRODUCT = "FETCH_ALL_PRODUCT";

// FOR CUSTOMER
export const GET_ALL_DUE_CUSTOMER = "GET_ALL_DUE_CUSTOMER";
export const CREATE_DUE_CUSTOMER = "CREATE_DUE_CUSTOMER";
export const UPDATE_DUE_CUSTOMER = "UPDATE_DUE_CUSTOMER";
export const DELETE_DUE_CUSTOMER = "DELETE_DUE_CUSTOMER";

// FOR CART
export const ADD_TO_CART = "ADD_TO_CART";
export const REMOVE_FROM_CART = "REMOVE_FROM_CART";
export const CLEAR_CART = "CLEAR_CART"

// FOR SYSTEM USER 

export const GET_ALL_USER = "GET_ALL_USER";
export const CREATE_SYSTEM_USER = "CREATE_SYSTEM_USER";
export const DELETE_SYSTEM_USER = "DELETE_SYSTEM_USER";
export const EDIT_SYSTEM_USER = "EDIT_SYSTEM_USER";